my_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: URB63596

      # User/password auth
      user: DOLPHIN
      password: Maapaa@1603

      #role: [user role]
      database: medi_assist_mimic_iv
      warehouse: my_warehouse
      schema: raw
      #threads: [1 or more]
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None