{{ config(
    materialized='table'
) }}


SELECT
    ROW_NUMBER() OVER (ORDER BY HADM_ID) AS ADM_RECORD_ID,
    HADM_ID AS ADM_ADMISSION_ID,
    SUBJECT_ID,
    ADMITTIME AS ADM_ADMIT_TIME,
    DISCHTIME AS ADM_DISCH_TIME,
    DEATHTIME AS ADM_DEATH_TIME,
    ADMISSION_LOCATION AS ADM_ADMISSION_LOCATION,
    DISCHARGE_LOCATION AS ADM_DISCHARGE_LOCATION,
    INSURANCE AS ADM_INSURANCE,
    MARITAL_STATUS AS ADM_MARITAL_STATUS,
    RACE AS ADM_RACE,
    LENGTH_OF_STAY
FROM
    {{ source('staging_mimic', 'STG_ADMISSIONS') }}