CREATE OR REPLACE TABLE mimic_iv_medi_assist.LLM_SCHEMA.DIM_LLM_MEDICAL_CODES (
    RECORD_ID NUMBER(18,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,  -- Unique surrogate key
    DIS_RECORD_ID NUMBER(18,0),        -- Foreign key to link to the discharge table
    ICD_CODE VARCHAR(50)            -- ICD-10 Code generated by the LLM         -- 'D' for Diagnosis, 'P' for Procedure',
    PRIMARY KEY (RECORD_ID)           -- Primary key constraint
);
