{{ config(materialized='table') }}

WITH raw_admissions AS (
    SELECT
        COALESCE(SUBJECT_ID, 0) AS SUBJECT_ID,
        COALESCE(HADM_ID, 0) AS HADM_ID,
        COALESCE(ADMITTIME, '1900-01-01 00:00:00') AS ADMITTIME,
        COALESCE(DISCHTIME, '1900-01-01 00:00:00') AS DISCHTIME,
        COALESCE(DEATHTIME, '1900-01-01 00:00:00') AS DEATHTIME,
        --COALESCE(EDREGTIME, '1900-01-01 00:00:00') AS EDREGTIME,
        --COALESCE(EDOUTTIME, '1900-01-01 00:00:00') AS EDOUTTIME,
        --COALESCE(ADMISSION_TYPE, 'UNKNOWN') AS ADMISSION_TYPE,
        --COALESCE(ADMIT_PROVIDER_ID, 'UNKNOWN') AS ADMIT_PROVIDER_ID,
        COALESCE(ADMISSION_LOCATION, 'UNKNOWN') AS ADMISSION_LOCATION,
        COALESCE(DISCHARGE_LOCATION, 'UNKNOWN') AS DISCHARGE_LOCATION,
        COALESCE(INSURANCE, 'UNKNOWN') AS INSURANCE,
        --COALESCE(LANGUAGE, 'UNKNOWN') AS LANGUAGE,
        COALESCE(MARITAL_STATUS, 'UNKNOWN') AS MARITAL_STATUS,
        COALESCE(RACE, 'UNKNOWN') AS RACE,
        --COALESCE(HOSPITAL_EXPIRE_FLAG, 0) AS HOSPITAL_EXPIRE_FLAG,
        COALESCE(DATEDIFF('day', ADMITTIME, DISCHTIME), 0) AS LENGTH_OF_STAY,
        --COALESCE(EXTRACT(YEAR FROM ADMITTIME), 1900) AS ADMIT_YEAR,
        --COALESCE(EXTRACT(MONTH FROM ADMITTIME), 1) AS ADMIT_MONTH,
        --COALESCE(EXTRACT(DAY FROM ADMITTIME), 1) AS ADMIT_DAY
    FROM {{ source('raw_mimic', 'RAW_ADMISSIONS') }}  -- Reference to the source table
    WHERE SUBJECT_ID IS NOT NULL
    AND HADM_ID IS NOT NULL
)

SELECT * FROM raw_admissions
